# EquiLens - Cross-Platform Docker System
# Compatible with Windows, macOS, and Linux
# GPU acceleration when available

services:
    # Ollama service for AI models
    ollama:
        image: ollama/ollama:latest
        container_name: equilens-ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama
        networks:
            - equilens-network

        # Cross-platform GPU support (optional)
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
            - OLLAMA_HOST=0.0.0.0:11434
            - OLLAMA_ORIGINS=*
            - OLLAMA_KEEP_ALIVE=24h

        restart: unless-stopped

        # Health monitoring
        healthcheck:
            test: ["CMD", "ollama", "--version"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

        command: ["serve"]

    # EquiLens application service
    equilens-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: equilens-app

        volumes:
            - .:/workspace:cached
            # Docker socket for container management (if needed)
            # Uncomment based on platform:
            # Windows: //var/run/docker.sock:/var/run/docker.sock
            # macOS/Linux: /var/run/docker.sock:/var/run/docker.sock

        working_dir: /workspace

        ports:
            - "8080:8080"  # Web interface

        networks:
            - equilens-network

        depends_on:
            ollama:
                condition: service_healthy

        environment:
            - OLLAMA_BASE_URL=http://ollama:11434
            - PYTHONPATH=/workspace
            - EQUILENS_DATA_DIR=/workspace/data
            - EQUILENS_RESULTS_DIR=/workspace/results
            - EQUILENS_LOGS_DIR=/workspace/logs
            - EQUILENS_WEB_PORT=8080

        restart: unless-stopped

        # Interactive mode for CLI usage
        stdin_open: true
        tty: true

        # Default command - can be overridden
        command: ["tail", "-f", "/dev/null"]

# Network for container communication
networks:
    equilens-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16

# Persistent volumes for model storage
volumes:
    ollama_data:
        driver: local
