services:
  equilens:
    build:
      context: .
      dockerfile: Dockerfile
    image: equilens:latest
    container_name: equilens-app
    ports:
      - "7860:7860"
      - "8000:8000"
    volumes:
      - equilens_data:/workspace/data
      # For development: mount source code for live editing
      # - ./src:/workspace/src:ro
      - ./public:/workspace/public:ro
    # Note: network_mode: host doesn't work on Docker Desktop for Windows
    # Use explicit port mapping instead
    environment:
      # Note: PYTHONPATH, PYTHONUNBUFFERED, PYTHONIOENCODING set in Dockerfile
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_API_BASE=http://host.docker.internal:11434/api
      - EQUILENS_DATA_DIR=/workspace/data
      - EQUILENS_RESULTS_DIR=/workspace/data/results
      - EQUILENS_LOGS_DIR=/workspace/data/logs
      - EQUILENS_CORPUS_DIR=/workspace/src/Phase1_CorpusGenerator/corpus
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - GRADIO_ANALYTICS_ENABLED=false
      - GRADIO_THEME=default
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  equilens_data:
    driver: local
    name: equilens-data
