"""
Results export functionality.
"""

import shutil
import tempfile
from pathlib import Path


def create_results_export(results_dir: Path) -> str | None:
    """
    Create a .zip export of results including all visualizations, reports, and raw data.

    Args:
        results_dir: Path to results directory

    Returns:
        Path to created zip file, or None if failed
    """
    try:
        # Create temporary directory for organizing export
        with tempfile.TemporaryDirectory() as temp_dir:
            export_dir = Path(temp_dir) / results_dir.name
            export_dir.mkdir()

            # Copy all PNG files (visualizations)
            for png_file in results_dir.glob("*.png"):
                shutil.copy2(png_file, export_dir / png_file.name)

            # Copy HTML report
            html_report = results_dir / "bias_analysis_report.html"
            if html_report.exists():
                shutil.copy2(html_report, export_dir / "bias_analysis_report.html")

            # Copy Markdown report
            md_report = results_dir / "bias_analysis_report.md"
            if md_report.exists():
                shutil.copy2(md_report, export_dir / "bias_analysis_report.md")

            # Copy all CSV files (raw data)
            for csv_file in results_dir.glob("*.csv"):
                shutil.copy2(csv_file, export_dir / csv_file.name)

            # Copy any JSON files
            for json_file in results_dir.glob("*.json"):
                shutil.copy2(json_file, export_dir / json_file.name)

            # Create README for the export
            readme_content = f"""# EquiLens Results Export

**Results Directory**: {results_dir.name}

## Contents

### Visualizations (PNG files)
- All charts and graphs generated during analysis
- Each chart includes a descriptive title

### Reports
- `bias_analysis_report.html` - Interactive HTML report with embedded visualizations
- `bias_analysis_report.md` - Markdown report with linked visualizations

### Raw Data
- CSV files containing the raw audit results
  - `logprobs_used` column indicates whether each test used log-probability scoring (True) or timing fallback (False)
  - `surprisal_score` column contains the bias score (interpretation depends on scoring method)
- JSON configuration and summary files (if present)
  - Summary JSON includes scoring method breakdown (logprobs vs timing counts)

## Scoring Methods

EquiLens supports two scoring approaches:
- **Log-probability scoring** (requires Ollama >= 0.12.11): Uses true model log-probabilities for bias detection. Higher scores = more model uncertainty = potential bias.
- **Timing fallback**: Uses eval_duration / eval_count as a proxy when logprobs are unavailable. Lower scores = stronger bias.

Check the `logprobs_used` column in CSV data or the report headers for which method was used.

## Viewing Results

### HTML Report
1. Open `bias_analysis_report.html` in any modern web browser
2. All visualizations are embedded as base64 images for offline viewing
3. Scoring method is displayed in the report header

### Markdown Report
1. Open `bias_analysis_report.md` in a Markdown viewer
2. Visualizations are linked to PNG files in the same directory

## Chart Descriptions

Each visualization shows different aspects of the bias analysis:

- **Violin Plot**: Distribution of bias scores across categories
- **Heatmap Matrix**: Color-coded mean bias scores by category
- **Effect Sizes**: Cohen's d values showing bias magnitude
- **Box Plot**: Statistical distributions per profession
- **Scatter Correlations**: Relationship between variables
- **Time Series**: Progression of scores across tests
- **Comprehensive Dashboard**: Multi-panel overview

---
*Generated by EquiLens - AI Bias Detection Platform*
"""

            readme_path = export_dir / "README.md"
            readme_path.write_text(readme_content, encoding="utf-8")

            # Create zip archive
            zip_path = results_dir.parent / f"{results_dir.name}_export"
            shutil.make_archive(
                str(zip_path), "zip", export_dir.parent, export_dir.name
            )

            final_zip = f"{zip_path}.zip"

            return final_zip

    except Exception as e:
        print(f"❌ Export creation failed: {e}")
        return None
